const DIFFICULTY = 4;
const MINE_RATE = 3000;
const INITIAL_BALANCE = 20;
const INITIAL_COUNT = 0;
const MINING_REWARD = 50;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  INITIAL_BALANCE,
  INITIAL_COUNT,
  MINING_REWARD,
};
