const DIFFICULTY = 100;
// const DIFFICULTY = 4;
const MINE_RATE = 3000;
const INITIAL_BALANCE = 20;
const INITIAL_BALANCE_2 = 10;
const INITIAL_COUNT = 0;

module.exports = {
  DIFFICULTY,
  MINE_RATE,
  INITIAL_BALANCE,
  INITIAL_BALANCE_2,
  INITIAL_COUNT,
};
